// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaUqdmx2GrA9glxyHobEArmUnvhJFZE-E',
    appId: '1:1045930050002:web:3a5b4627be5cd5f819880b',
    messagingSenderId: '1045930050002',
    projectId: 'groceries-2e670',
    authDomain: 'groceries-2e670.firebaseapp.com',
    storageBucket: 'groceries-2e670.appspot.com',
    measurementId: 'G-MGD038RZFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDujNPX2ZsZUiS5gzFIerEeJSwIhDmrH8I',
    appId: '1:1045930050002:android:49d1fff0686d5da819880b',
    messagingSenderId: '1045930050002',
    projectId: 'groceries-2e670',
    storageBucket: 'groceries-2e670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvIZSQInKa9UFXxO220B_7nQn7zNrcaWs',
    appId: '1:1045930050002:ios:c75c82dd0a353f5f19880b',
    messagingSenderId: '1045930050002',
    projectId: 'groceries-2e670',
    storageBucket: 'groceries-2e670.appspot.com',
    androidClientId: '1045930050002-nfr867oi6qkuj5he18ne35cmbli715jo.apps.googleusercontent.com',
    iosClientId: '1045930050002-tcqevba0hkop4i1rdl1k5brqvfnfduup.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvIZSQInKa9UFXxO220B_7nQn7zNrcaWs',
    appId: '1:1045930050002:ios:c75c82dd0a353f5f19880b',
    messagingSenderId: '1045930050002',
    projectId: 'groceries-2e670',
    storageBucket: 'groceries-2e670.appspot.com',
    androidClientId: '1045930050002-nfr867oi6qkuj5he18ne35cmbli715jo.apps.googleusercontent.com',
    iosClientId: '1045930050002-tcqevba0hkop4i1rdl1k5brqvfnfduup.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryAdminPanel',
  );
}
